server:
  port: 8081

spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    async:
      request-timeout: 300000 # 60초 (기본은 30초)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  task:
    scheduling:
      pool:
        size: 2

logging:
  level:
    tracer: TRACE
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace